# Configuración para los Routers (mongos)

systemLog:
  destination: file
  path: /dev/stdout # Envía logs a la salida estándar de Docker
  logAppend: true

net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS 
    certificateKeyFile: /etc/ssl/mongo/mongodb.pem
    CAFile: /etc/ssl/mongo/ca.crt
    clusterFile: /etc/ssl/mongo/mongodb.pem

    allowConnectionsWithoutCertificates: true

setParameter:
  diagnosticDataCollectionEnabled: false
  
security:
  keyFile: /etc/mongo/mongo.keyfile

sharding:
  configDB: rs-config/mongo-config-srv1:27019,mongo-config-srv2:27019,mongo-config-srv3:27019