# Configuración para Nginx (Balanceo de carga TCP)

events {
    worker_connections 1024;
}

stream {
    # Pool de servidores mongos
    upstream mongos_cluster {
        # least_conn; # Opcional: balancear a la conexión con menos carga
        server mongo-router-1:27017;
        server mongo-router-2:27017;
    }

    # Servidor virtual que escucha
    server {
        listen 27017; 
        
        # Reenvía el tráfico (passthrough de TLS)
        proxy_pass mongos_cluster;
        
        # Opcional: Tiempos de espera
        # proxy_connect_timeout 5s;
        # proxy_timeout 20s;
    }
}