# Configuración base para los Shard Servers (rs-shard1, 2, 3)

storage:
  dbPath: /data/db

systemLog:
  destination: file
  path: /dev/stdout # Envía logs a la salida estándar de Docker
  logAppend: true

net:
  port: 27017
  bindIp: 0.0.0.0
  tls:
    mode: requireTLS 
    certificateKeyFile: /etc/ssl/mongo/mongodb.pem # Ruta *dentro* del contenedor
    CAFile: /etc/ssl/mongo/ca.crt              # Ruta *dentro* del contenedor
    allowConnectionsWithoutCertificates: true

security:
  # Autenticación EXTERNA (usuarios/contraseñas) ENCENDIDA
  authorization: enabled
  authenticationMechanisms:
    - SCRAM-SHA-256
  
  # Autenticación INTERNA (con "password compartido") ENCENDIDA
  keyFile: /etc/mongo/mongo.keyfile

sharding:
  clusterRole: shardsvr

replication:
  replSetName: "PLEASE-OVERRIDE"

